version: '3.8'
services:
  db:
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    environment:
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
    ports:
      - '543:5432'
    restart: always
    volumes:
      - /var/lib/postgresql/data:/var/lib/postgresql/data
    container_name: portdolio_database

  init_db:
    build:
      context: ./backend/db
      dockerfile: Dockerfile
    environment:
      DB_PORT: 5433
      DB_HOST: localhost
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: db
    depends_on:
      - db

volumes:
  db-data:
