version: '3'

services:
  db:
    image: postgres
    container_name: postgres-container
    environment:
      DB_HOST: localhost
      DB_PASSWORD: password
    ports:
      - '5433:5432'

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '5000:5000'
    depends_on:
      - db
